services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: vetgy
      POSTGRES_PASSWORD: 255233255233
      POSTGRES_DB: moku_repos
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    ports:
      - "5433:5432"

volumes:
  pgdata:
